<?php
// Role → allowed route segments.
// Used by the sidebar to know which links to render,
// and can be used to gate route access programmatically.

define('ROLES', [
    'hod_ict' => [
        'dashboard',
        'assets', 'assets/create', 'assets/edit', 'assets/archive',
        'assets/reclassify', 'assets/disposals', 'assets/moved',
        'assets/untracked', 'assets/add-id', 'assets/wip-transfer',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'reports/quarterly-class', 'reports/quarterly-asset',
        'exports/excel', 'exports/pdf',
        'admin/users', 'admin/asset-classes', 'admin/suppliers',
        'admin/locations', 'admin/asset-users', 'admin/asset-types',
        'admin/dollar-rate',
    ],
    'schedule_officer' => [
        'dashboard',
        'assets', 'assets/create', 'assets/edit', 'assets/archive',
        'assets/reclassify', 'assets/disposals', 'assets/moved',
        'assets/untracked', 'assets/add-id', 'assets/wip-transfer',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'reports/quarterly-class', 'reports/quarterly-asset',
        'exports/excel', 'exports/pdf',
        'admin/users', 'admin/asset-classes', 'admin/suppliers',
        'admin/locations', 'admin/asset-users', 'admin/asset-types',
        'admin/dollar-rate',
    ],
    'accountant' => [
        'dashboard',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'reports/quarterly-class', 'reports/quarterly-asset',
        'exports/excel', 'exports/pdf',
    ],
    'budget_officer' => [
        'dashboard',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'exports/excel', 'exports/pdf',
    ],
    'director_finance' => [
        'dashboard',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'reports/quarterly-class', 'reports/quarterly-asset',
        'exports/excel', 'exports/pdf',
    ],
    'sia' => [
        'dashboard',
        'reports', 'reports/summary', 'reports/summary-usd',
        'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/depreciation-charge', 'reports/additions',
        'reports/accum-depreciation', 'reports/fully-depreciated',
        'reports/historical-cost', 'reports/disposals',
        'reports/by-category', 'reports/by-location',
        'exports/excel', 'exports/pdf',
    ],
    'dsu' => [
        'dashboard',
        'admin/asset-classes', 'admin/locations',
        'reports', 'reports/all-assets', 'reports/all-assets-usd',
        'reports/individual-asset', 'reports/class-report',
        'reports/disposals', 'reports/by-category', 'reports/by-location',
        'exports/excel', 'exports/pdf',
    ],
]);
